# Generated by Django 3.0.8 on 2020-07-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200711_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reserve_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reserved', 'Reserved'), ('In Use', 'In Use'), ('Fulfilled', 'Fulfilled')], max_length=200, null=True),
        ),
    ]
