# Generated by Django 3.0.8 on 2020-07-15 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200712_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reserve_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
