# Generated by Django 3.0.8 on 2020-07-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200715_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('Non-Member', 'Non-Member'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Dollars', 'Dollars')], max_length=200, null=True),
        ),
    ]
