# Generated by Django 3.0.8 on 2020-07-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200716_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='accounts/images/profile_default_img.png', null=True, upload_to=''),
        ),
    ]
